services:
  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env.production
    environment:
      NODE_ENV: production
      PORT: ${PORT:-3001}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${PORT:-3001}:3001"

  frontend:
    build:
      context: ./frontend
    env_file:
      - ./frontend/.env.production
    environment:
      VITE_API_URL: ${VITE_API_URL}
    ports:
      - "3000:3000"  # adjust if your frontend runs on another port
    depends_on:
      - backend